apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "22"
  deepak: "33"
  ui_properties_file_name: "user-interface.properties"

