apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  namespace: argocd
  labels:
    app: ngnix 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: nginx:1.14.2
        ports:
        - containerPort: 80  

