apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-room-connector-agent
  namespace: sip-room-connector
spec:
  replicas: 1
---
apiVersion: v1
data:
  PUBSUB_SUBSCRIPTION_ID: sip-room-connector-subscription
kind: ConfigMap
metadata:
  name: sip-room-connector-agent-config
  namespace: sip-room-connector
