apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: recorder-agent-secret
  namespace: recorder
spec:
  encryptedData:
    secret: AgAIVWCSofRsjTNdCHOFX0Mvdk0qbL/Pk6iOYPIYPv7OtADo3UftU5f+KVV77zvBKUTu/vkID8gKsCklSMhno5DUIGwH5dX6aawsQk6tI0pbr7FcVGWDWa75uF/t4q3KVVj4XcuccdAvOeGhxx0oGl0bFlpa5rXyMxsOOx1hvo1cZ1SE6iiXnmihSmaPQQ+ZbYoue3X5AyR+yeHiiBSDXsU4tlq+rK7abgF6QMUgTCMa5Tu+P/1ALoVHEjCqH75QOPENRbj2HcnALLDSYq7E/q64HHmX8tSq1cojB5hSxBYWjT8vxVNp9XDvjXtdLyG5IXR9b9d/RzksvQKiuB9I7JZGAPbi+uYK+DS6VqmTUFEUbDu8zUsmtedMdtQ82N71OuAbca4nW7d+9Ur2IGJFJrp62gXIihc/ovS48CNh7MMR5qprs4yi0I4tjPK+twIsPB0gzpa9gNXcAJUUSGReZNyQzw4IPHAX9awVUV6SiyY3iP691xt9t0t1fZ+TLUedvAc9PpoNo7PxFRqqntBUafqNxM+cfvQtOYjUzvTFDKSVDwBCA4ItEfbN7IxKOYlLDSXvHaFzm5b8Es4ZBbjpBEVlcdX1L4UQsh27+84k9Kvo7Zt+8tdZVSP7lehmlNnQ5r3kvrgEjtZI1SnTn7RlMkRE7jzgtnILOKYuc3pN4JBu/2suPpn6y+SaUNGdalMQhqM4XGgr6mYZU8S9R5B6Sb4usHDwu1bYsBXUofe+RyIX4g==
  template:
    metadata:
      creationTimestamp: null
      name: recorder-agent-secret
      namespace: recorder

