# Recorder agent types
RECORDER_AGENT_TYPES = ['video-recording', 'streaming-recording', 'sip-room-connector']
RECORDER_AGENT_TYPE_VIDEO = RECORDER_AGENT_TYPES[0]
RECORDER_AGENT_TYPE_STREAMING = RECORDER_AGENT_TYPES[1]
RECORDER_AGENT_TYPE_SIP_ROOM_AGENT = RECORDER_AGENT_TYPES[2]
