apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-ui
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  BASE_config_value_new: "hello"
  BASE_config_update: "Testing the tags"
  BASE_config_update_2: "Testing the tags update 2nd time"
