apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://rs-dal-km1-staging.ubervoip.net:6443
      - cluster: engineering-prod
        url: https://rs-dal-km1-staging.ubervoip.net:6443
      - cluster: finance-preprod
        url: https://rs-dal-km1-staging.ubervoip.net:6443
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/deepakdialpad/argocd-example-apps.git
        targetRevision: argocd-example-1
        path: application-sets/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
