apiVersion: v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: ngnix 
spec:
  replicas: 1
  selector:
    matchlabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: ngnix
        image: nginx:1.14.2
        ports:
        - containerPort: 80 