apiVersion: builtin
kind: LabelTransformer
metadata:
  name: streaming-recorder-labels
labels:
  tags.datadoghq.com/env: uberconf
  tags.datadoghq.com/service: streaming-recorder
  tags.datadoghq.com/version: DM2021-08-25-6-g6241a59f102
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
