apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "100"
  ui_properties_file_name: "user-interface.properties"
  from_cut_branch: "from cut branch"


