apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-recorder-agent
  namespace: recorder
spec:
  replicas: 1
---
apiVersion: v1
data:
  PUBSUB_SUBSCRIPTION_ID: streaming-recorder-subscription-bpham
kind: ConfigMap
metadata:
  name: streaming-recorder-config
  namespace: recorder
