apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recorder
resources:
  - 00-namespace.yaml 
  - 01-serviceaccount.yaml
  - 02-role.yaml
  - 03-rolebinding.yaml
  - 04-configmap.yaml
  - 05-deployment.yaml
  